---
- name: execute bash script
  hosts: all
  become: true
  tasks:
    - name: Execute LAMP deployment script
      script: /home/vagrant/lamp_script.sh

    - name: Check if PHP application is accessible
      uri:
        url: http://192.168.33.8/index.php
        return_content: yes
      register: webpage
      failed_when: "'Laravel' not in webpage.content"
    
    - name: Create cron job for server uptime
      cron:
        name: "Check uptime"
        minute: "0"
        hour: "0"
        job: "uptime >> /var/log/uptime.log"